app_name: DOH-EMS API
environment: development

server:
  host: localhost
  port: "8080"
  readtimeout: 10
  writetimeout: 10
  idle_timeout: 120

database:
  host: 127.0.0.1
  port: 5432
  user: "doh_ems"
  password: "password"
  name: "doh_ems"
  ssl_mode: "disable"
  timezone: Asia/Bangkok